### ISSUE TITLE
Trigger A loops sometimes

### ISSUE THREAD

**Issue by acarito** [synesthesiacs/wyrdheim-pi#4]
Sometimes trigger A would loop a couple times before returning to the main loop. it is erratic/inconsitent - as far as I could tell.

**Comment by Continuities** [comment]
Hm, that's weird. I wouldn't expect that to happen unless multiple GPIO triggers were occurring. I'll try to reproduce.

**Comment by acarito** [comment]
I triggered it to show Adam, then sat down at the table and we both noticed that it started again. it was weird. happened only twice.

**Comment by Continuities** [comment]
Probably gpio bounce, which is why it doesn't happen with mocked gpio. I'll debounce the signal, and hopefully that'll clear it up.
