### ISSUE TITLE
Trigger B, stops

### ISSUE THREAD

**Issue by acarito** [synesthesiacs/wyrdheim-pi#6]
Trigger B when first run on a specific gpio, should play then change the loop. It should also be allowed to play again (as it will have 3 more triggers), per gpio, but not change the loop.

**Comment by Continuities** [comment]
Wait, what? That wasn't in the spec!

So GPIO triggers should *always* play the trigger sound, but only increment
the drone the first time?

**Comment by acarito** [comment]
It does say it in the spec but not in the clearer language that we started using as we were troubleshooting.
But, yes, that's right. It should trigger each time for the 4 runes (or "sensors" as it says n the spec)
and only increment the loop the first time.

**Comment by acarito** [comment]
and only increment the loop the first time.
